baseurl = "http://sointers.github.io/"
languageCode = "en-GB"
title = "Sointer"
paginate = 5
DisqusShortname = "sointer"
Copyright = "All rights reserved - 2015"
theme = "casper"
[params]
  description = "Whenever a man does a thoroughly stupid thing, it is always from the noblest motives."
  cover = "images/adam.jpg"
  author = "Boaz Sobrado"
  authorlocation = "Budapest, Hungary"
  authorwebsite = "http://sointers.github.io/"
  bio= "Mathematics."
  logo = "images/logo.png"
  githubName = "sointers"
  twitterName = "sointers"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false


[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"
