baseurl = "http://vjeantet.fr/"
languageCode = "en-GB"
title = "Sointer"
paginate = 5
DisqusShortname = "vjeantet"
Copyright = "All rights reserved - 2015"
theme = "casper"
[params]
  description = "It is a sad thing to think of, but there is no doubt that genius lasts longer than beauty. That accounts for the fact that we all take such pains to over-educate ourselves. In the wild struggle for existence, we want to have something that endures, and so we fill our minds with rubbish and facts, in the silly hope of keeping our place."
  cover = "images/adam.jpg"
  author = "Boaz Sobrado"
  authorlocation = "Budapest, Hungary"
  authorwebsite = "http://vjeantet.fr"
  bio= "Mathematics."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  githubName = "sointers"
  twitterName = "sointers"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false


[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"
